services:
  db:
    image: postgres:16
    container_name: smit_pg
    environment:
      POSTGRES_USER: smit
      POSTGRES_PASSWORD: smit
      POSTGRES_DB: smit_dev
    ports:
      - "5432:5432"
    volumes:
      - smit_pgdata:/var/lib/postgresql/data

volumes:
  smit_pgdata:
